# Generated by Django 5.2.5 on 2025-08-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='author',
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
